// Script for generate report reasons scss for lzt-report-icons userscript

import path from "node:path";
import reasons, {
  color,
  hoverColor,
  type Reason,
} from "../lzt-report-icons/reasons";

const copyright = `/*
  This file is autogenerated. DON'T edit it manually.

  Exclusive for LZT Upgrade.
  Socials:
    - Telegram (https://t.me/lzt_upgrade)
    - Github (https://github.com/lzt-upgrade)
  Authors:
    - Toil (https://lolz.live/toil/)
*/`;

let code = `${copyright}

@mixin svg-icon {
  width: 0.65em !important;
  height: 0.65em !important;
  align-self: center !important;
  background-size: 100% !important;
  background-repeat: no-repeat !important;
  padding: 5px !important;
  margin: -5px 0 !important;
}

`;

async function generateReasonsCSS() {
  code += Object.entries(reasons)
    .map(([key, val]: [string, Reason]) => {
      const scale = val.scale ?? 1;
      return `.lztup-report-${key} {
  @include svg-icon;
  background-image: ${val.iconData.replaceAll("$color", color)} !important;${
    scale !== 1 ? `scale: ${scale};` : ""
  }
}

.reportReasons label:has(> .lztup-report-${key}):hover .lztup-report-${key} {
  background-image: ${val.iconData.replaceAll(
    "$color",
    hoverColor,
  )} !important;${scale !== 1 ? `scale: ${scale};` : ""}
}
`;
    })
    .join("\n");

  await Bun.write(
    path.join(__dirname, "..", "lzt-report-icons", "report-icons.scss"),
    code,
  );
}

await generateReasonsCSS();
